// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxmd87z719O936NBw-enjKeElmoaWUdSQ',
    appId: '1:46019019216:web:d96984e987a2435d25b9d5',
    messagingSenderId: '46019019216',
    projectId: 'mamaiknow-159d7',
    authDomain: 'mamaiknow-159d7.firebaseapp.com',
    storageBucket: 'mamaiknow-159d7.appspot.com',
    measurementId: 'G-EY01QVWXE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgFCyTdAHg4_8PYUxorfOb_zhNju7f8Yw',
    appId: '1:46019019216:android:a9cca5ab8769a31625b9d5',
    messagingSenderId: '46019019216',
    projectId: 'mamaiknow-159d7',
    storageBucket: 'mamaiknow-159d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDopLBtBLk_dV3P8TQaNQRlojpyZUJLKaQ',
    appId: '1:46019019216:ios:8d9eb293b3f6e70225b9d5',
    messagingSenderId: '46019019216',
    projectId: 'mamaiknow-159d7',
    storageBucket: 'mamaiknow-159d7.appspot.com',
    iosBundleId: 'com.zeepalm.mamaiknow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDopLBtBLk_dV3P8TQaNQRlojpyZUJLKaQ',
    appId: '1:46019019216:ios:8d9eb293b3f6e70225b9d5',
    messagingSenderId: '46019019216',
    projectId: 'mamaiknow-159d7',
    storageBucket: 'mamaiknow-159d7.appspot.com',
    iosBundleId: 'com.zeepalm.mamaiknow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxmd87z719O936NBw-enjKeElmoaWUdSQ',
    appId: '1:46019019216:web:1519a5c6798b555a25b9d5',
    messagingSenderId: '46019019216',
    projectId: 'mamaiknow-159d7',
    authDomain: 'mamaiknow-159d7.firebaseapp.com',
    storageBucket: 'mamaiknow-159d7.appspot.com',
    measurementId: 'G-ZE3Y2NDDPX',
  );
}
